### ISSUE TITLE
ggplot2

### ISSUE THREAD

**Issue by jbkunst** [visualizacion-uc/procesamiento-y-analisis-de-datos#4]
Don @pachamaltese ,

Que tanto enseñará de `ggplot2`?

**Comment by pachadotdev** [comment]
@jbkunst lo que más pueda !! todo usando `%>%` ya que el semestre pasado en la eval docente me dijeron que el `<-` era una m***** comparado con `=` y `==`

**Comment by pachadotdev** [comment]
@jbkunst esto muestra el 95% de lo que pretendo q entiendan https://visualizacion-uc.github.io/procesamiento-y-analisis-de-datos/guias/guia-de-ejercicios.html

**Comment by jbkunst** [comment]
Ok, gracias.

**Comment by jbkunst** [comment]
Aps! Y no creo que dicho comentario sea una razón para no usar `<-`.

**Comment by pachadotdev** [comment]
me debo a mi público :)
